buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.linkaProject.LinkaAi'
    compileSdkVersion 30 
    defaultConfig {
        applicationId "com.linkaProject.LinkaAi"
        minSdkVersion 3    
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }
}