buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

apply plugin: 'com.android.application'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.linka.app'
    compileSdkVersion 30  // O compilador moderno precisa da API 30 para processar o AAPT2 sem erros

    defaultConfig {
        applicationId "com.linka.app"
        minSdkVersion 3    // Garante compatibilidade real com Android 1.5 (Cupcake)
        versionCode 1
        versionName "1.0"
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }
    }
}